export enum DEX_ENUM {
  ONEINCH = "1inch",
  AKKA = "AKKA",
  PARASWAP = "ParaSwap",
  ZEROXAPI = "0xAPI",
  WRAPTOKEN = "WrapToken",
  OPENOCEAN = "OpenOcean",
  UNISWAP = "Uniswap",
  KYBERSWAP = "Kyberswap",
  PARASWAPV6 = "ParaSwapV6",
  ODOS = "ODOS",
  ZEROXAPIV2 = "0xAPIV2",
  MAGPIE = "Magpie",
  RABBY = "Rabby",
}
